project:
  type: website

website:
  title: ""
  search: false 
  favicon: "images/prb_logo_smaller.png"
  navbar:
    background: "#f8f9fa"
    logo: "images/prb_logo.png"
    left: 
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: false
    page-layout: full
    css: styles.css
    link-external-newwindow: true
    link-external-icon: true
    # link-external-filter: '^(?:http:|https:)\/\/ansperformance\.eu\/|^(?:http:|https:)\/\/.*ace-handbook\.netlify\.app\/'
    
execute:
  echo: false
  warning: false