project:
  type: website

website:
  title: ""
  navbar:
    background: "#f8f9fa"
    search: true
    logo: "images/prb_logo.png"
    left: 
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Interactive dashboard
      - href: about.qmd
        text: About
  page-footer: "To be added" 
  
format:
  html:
    theme: cosmo
    toc: false
    page-layout: full
    css: styles.css
    
execute:
  echo: false
  warning: false