project:
  type: website
  output-dir: docs

website:
  title: ""
  search: false
  navbar:
    background: "#f8f9fa"
    logo: "images/prb_logo.png"
    left: 
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: Interactive dashboard
      - href: about.qmd
        text: About
      - href: https://transport.ec.europa.eu/transport-modes/air/single-european-sky/ses-performance-and-charging/publications_en
        text: Publications {{< fa external-link-alt >}}
        target: "_blank"
      # - href: https://www.eurocontrol.int/prudata/dashboard/
      #   text: SES Data Portal {{< fa external-link-alt >}}
  page-footer: 
    center: 
      - href: mailto:prb-office@prb.eusinglesky.eu
        text: "{{< fa envelope >}} prb-office@prb.eusinglesky.eu"
  
format:
  html:
    theme: cosmo
    toc: false
    page-layout: full
    css: styles.css
    link-external-newwindow: true
    link-external-icon: true
    # link-external-filter: '^(?:http:|https:)\/\/ansperformance\.eu\/|^(?:http:|https:)\/\/.*ace-handbook\.netlify\.app\/'
    
execute:
  echo: false
  warning: false